[package]
name = "toolcraft"
version = "0.1.3"
edition = "2024"
description = "A modular Rust toolkit"
authors = ["Ancient <gamesworldcraft@gmail.com>"]
license = "MIT"
repository = "https://github.com/code-serenade/toolcraft.git"
documentation = "https://docs.rs/toolcraft"

[dependencies]
thiserror = "2"
tokio = { version = "1.46", features = ["full"] }
regex = "1"
zip = "4"
quick-xml = { version = "0.38", features = ["encoding"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.22"
chrono = { version = "0.4", features = ["serde"] }
hmac = "0.12"
sha2 = "0.10"
hex = "0.4"
reqwest = { version = "0.12", features = ["json", "stream"] }
url = "2.5"
futures-util = "0.3"
bytes = "1"
minio = { version = "0.3" }
