# cargo-release configuration for toolcraft-axum-kit

# 允许的分支
allow-branch = ["main"]

# Git 配置
sign-commit = false
sign-tag = false
tag = true
push = false

# 发布配置
publish = true
verify = true

# 依赖更新配置
[[dependencies]]
name = "toolcraft-jwt"
upgrade = false  # 不自动升级版本

# 发布前检查
pre-release-hook = ["cargo", "test", "--package", "toolcraft-axum-kit"]

# commit 消息模板
pre-release-commit-message = "chore: release toolcraft-axum-kit v{{version}}"

# 标签配置
tag-message = "Release toolcraft-axum-kit v{{version}}"
tag-name = "axum-kit-v{{version}}"